// <auto-generated />
namespace chinchini.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Fix2ndStatusToLoan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fix2ndStatusToLoan));
        
        string IMigrationMetadata.Id
        {
            get { return "201404060314470_Fix2ndStatusToLoan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
